import {
    Footer,
    FooterBrand,
    FooterCopyright,
    FooterDivider,
    FooterLink,
    FooterLinkGroup,
    getTheme
} from 'flowbite-react';


import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/theme-provider"
import {ModeToggle} from "@/components/mode-toggle";
import {Navbar} from "@/components/ui/Navbar";
import {useTheme} from "next-themes";
import Link from "next/link";
import {Icons} from "@/components/ui/Icons";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Turbocontrol',
    description: 'Generated by create next app',

}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full">
        <body className={cn("h-full relative antialiased font-sans ", inter.className)}>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >


            <Navbar></Navbar>

            <main className={"relative flex flex-col min-h-screen "}>
                <div className={"flex-grow flex-1 "}>

                    {children}
                </div>
            </main>

            <Footer container className={"dark:bg-custom-gray bg-gray-200"}>
                <div className="w-full text-center">
                    <div className="w-full justify-between sm:flex sm:items-center sm:justify-between">
                        <div className={"flex flex-row gap-6 items-baseline"}>
                            <div className={"ml-4 flex flex-row"}>
                                <Link href={"/"}>
                                    <div className={"flex align-middle"}>

                                    <p className={"align-middle"}>Turbocontrol</p>
                                    <Icons.logo className={"h-10 w-10 dark:fill-white"}/>
                                    </div>

                                </Link>
                            </div>

                            <div className={"flex flex-col"}>
                                <p>Powered by:</p>

                                <img src={"./SIX_logo_a4_black_rgb.png"} alt={""} style={{scale: "0.65"}}/>


                            </div>
                        </div>
                        <FooterLinkGroup>
                            <FooterLink href="#">About</FooterLink>
                            <FooterLink href="#">Privacy Policy</FooterLink>
                            <FooterLink href="#">Licensing</FooterLink>
                            <FooterLink href="#">Contact</FooterLink>
                        </FooterLinkGroup>
                    </div>
                    <FooterDivider/>
                    <FooterCopyright href="#" by="Turbocontrol™" year={2024}/>
                </div>
            </Footer>

        </ThemeProvider>
        </body>
        </html>
    )
}
